export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_HACKS_SUCCESS = 'LOAD_HACKS_SUCCESS';
export const LOAD_HACKS_FAILURE = 'LOAD_HACKS_FAILURE';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_HACK_SUCCESS = 'CREATE_HACK_SUCCESS';
export const UPDATE_HACK_SUCCESS = 'UPDATE_HACK_SUCCESS';

export const LOAD_PRACTICETOPICS_SUCCESS = 'LOAD_PRACTICETOPICS_SUCCESS';
export const CREATE_PRACTICETOPICS_SUCCESS = 'CREATE_PRACTICETOPICS_SUCCESS';
export const UPDATE_PRACTICETOPICS_SUCCESS = 'UPDATE_PRACTICETOPICS_SUCCESS';

